name = "ThorAxe"
uuid = "cf6a4a95-c6c1-4b3e-818d-24edc886ccb5"
authors = ["Diego Javier Zea"]
version = "0.8.3"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"

[compat]
CondaPkg = "0.2"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
